import {StyleSheet} from 'react-native';

import COLORS from '../colors';

const BlendStyles = StyleSheet.create({
  container: {
    backgroundColor: COLORS.background,
    flex: 1,
    paddingHorizontal: 10,
  },
  backButton: {
    marginTop: 30,
    padding: 7,
    backgroundColor: COLORS.text,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  profilePhotoContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
  },
  userInfoContainer: {
    backgroundColor: COLORS.tabBar,
    borderRadius: 30,
    padding: 15,
    marginHorizontal: 10,
    marginTop: 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  userName: {
    color: COLORS.primary,
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  userDetails: {
    color: COLORS.text,
    fontSize: 18,
  },
  additionalInfoContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  cardContainer: {
    backgroundColor: COLORS.tabBar,
    borderRadius: 20,
    padding: 15,
    marginTop: 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  titleText: {
    fontSize: 20,
    color: COLORS.text,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 5,
  },
  nameText: {
    fontSize: 15,
    color: COLORS.text,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 5,
  },
  profilePhoto: {
    width: 100,
    height: 100,
    borderRadius: 10,
    alignSelf: 'center',
    marginBottom: 10,
  },
  infoText: {
    fontSize: 14,
    marginHorizontal: 5,
    color: COLORS.titlePurple,
  },
  textTitle: {
    color: COLORS.text,
    fontSize: 28,
    fontWeight: 'bold',
    alignSelf: 'center',
    marginBottom: 10,
  },
  textDescription: {
    color: COLORS.text,
    fontSize: 15,
    alignSelf: 'center',
    marginBottom: 20,
  },
  musicPreferences: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    marginTop: 0,
    marginBottom: 15,
  },
  musicPreferenceTile: {
    backgroundColor: COLORS.text,
    borderRadius: 6,
    paddingVertical: 10,
    alignItems: 'center',
    width: '30%',
  },
  musicPreferenceLabel: {
    fontSize: 12,
    color: COLORS.background,
    marginBottom: 0,
  },
  musicPreferenceText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: COLORS.background,
  },
  socialInfo: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    marginBottom: 10,
  },
  socialInfoColumn: {
    marginHorizontal: -50,
    alignItems: 'center',
    width: '30%',
    marginBottom: 0,
  },
  socialInfoTitle: {
    fontSize: 13,
    color: COLORS.text,
    marginBottom: 0,
  },
  socialInfoNumber: {
    fontSize: 20,
    marginBottom: 5,
    fontWeight: 'bold',
    color: COLORS.text,
  },
  userPhotosContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 10,
    marginBottom: 0,
  },
  column: {
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  square: {
    width: 160,
    height: 160,
    borderRadius: 10,
    marginVertical: 5,
  },
  verticalRectangle: {
    width: 160,
    height: 250,
    borderRadius: 20,
    marginVertical: 5,
    borderWidth: 2,
    borderColor: COLORS.text,
  },
  separator: {
    height: 10,
    backgroundColor: 'transparent',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginTop: 5,
    marginBottom: 15,
  },
  messageButton: {
    backgroundColor: COLORS.text,
    padding: 10,
    width: 130,
    alignItems: 'center',
    borderRadius: 6,
    borderWidth: 0,
    borderColor: COLORS.titlePurple,
  },
  addFriendButton: {
    backgroundColor: COLORS.primary,
    padding: 10,
    width: 130,
    alignItems: 'center',
    borderRadius: 6,
    borderWidth: 0,
    borderColor: COLORS.titlePurple,
  },
  buttonText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: 'bold',
  },
  buttonTextWhite: {
    color: COLORS.primary,
    fontSize: 12,
    fontWeight: 'bold',
  },
  tileTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'white',
    marginBottom: 5,
  },
  tileSubtitle: {
    fontSize: 12,
    color: 'white',
  },
  textOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 10,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    height: 60,
  },
});

export default BlendStyles;
