import {StyleSheet} from 'react-native';

import COLORS from '../colors';

const HomeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    alignItems: 'center',
    padding: 20,
  },
  textTitle: {
    fontSize: 24,
    color: COLORS.text,
    fontWeight: 'bold',
  },
  textDescription: {
    fontSize: 16,
    color: COLORS.text,
    marginTop: 10,
  },
  section: {
    marginTop: 10,
    paddingHorizontal: 15,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.text,
    marginBottom: 15,
  },
  tile: {
    width: 150,
    height: 150,
    borderRadius: 15,
    backgroundColor: COLORS.tabBar,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    marginBottom: 10,
  },
  bar: {
    width: 150,
    height: 75,
    borderRadius: 5,
    backgroundColor: COLORS.tabBar,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    marginBottom: 10,
  },
  barText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.text,
  },
  barImage: {
    width: '100%',
    height: '100%',
    borderRadius: 5,
    position: 'absolute',
  },
  barTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'white',
    marginBottom: 5,
  },
  barSubtitle: {
    fontSize: 12,
    color: 'white',
  },
  rectangleTile: {
    width: 300,
    marginVertical: 0,
  },
  tileText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.text,
  },
  tileImage: {
    width: '100%',
    height: '100%',
    borderRadius: 15,
    position: 'absolute',
  },
  textOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 10,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    height: 55,
  },
  tileTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'white',
    marginBottom: 5,
  },
  tileSubtitle: {
    fontSize: 12,
    color: 'white',
  },
  playButton: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: 'rgba(228, 215, 244, 1)',
    borderRadius: 5,
    padding: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  likeButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(228, 215, 244, 1)',
    borderRadius: 5,
    padding: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchContainer: {
    paddingHorizontal: 15,
  },
  searchResultsContainer: {
    padding: 10,
  },
  searchResultsOverlay: {
    position: 'absolute',
    top: 40,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(7, 3, 12, 0.9)',
    padding: 10,
    marginHorizontal: 15,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    zIndex: 1,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.text,
    borderRadius: 10,
  },
  searchInput: {
    flex: 1,
    padding: 12,
    fontSize: 12,
    color: COLORS.background,
  },
  searchIcon: {
    marginLeft: 10,
  },
  searchProfileImage: {
    width: 30,
    height: 30,
    borderRadius: 20,
    marginRight: 10,
    borderWidth: 1,
    borderColor: COLORS.text,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    padding: 10,
    marginBottom: 5,
  },
  searchResultTextContainer: {
    flexDirection: 'column',
  },
  searchResultText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: 'bold',
  },
  searchResultSubtext: {
    color: COLORS.text,
    fontSize: 12,
  },
});
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    alignItems: 'center',
    padding: 20,
  },
  textTitle: {
    fontSize: 24,
    color: COLORS.text,
    fontWeight: 'bold',
  },
  textDescription: {
    fontSize: 16,
    color: COLORS.text,
    marginTop: 10,
  },
  section: {
    marginTop: 10,
    paddingHorizontal: 15,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.text,
    marginBottom: 15,
  },
  tile: {
    width: 150,
    height: 150,
    borderRadius: 15,
    backgroundColor: COLORS.tabBar,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    marginBottom: 10,
  },
  rectangleTile: {
    width: 300,
    marginVertical: 0,
  },
  tileText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.text,
  },
  infoText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.text,
  },
  tileImage: {
    width: '100%',
    height: '100%',
    borderRadius: 15,
    position: 'absolute',
  },
  textOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 10,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    height: 55,
  },
  tileTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'white',
    marginBottom: 5,
  },
  tileSubtitle: {
    fontSize: 12,
    color: 'white',
  },
  playButton: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: 'rgba(228, 215, 244, 1)',
    borderRadius: 5,
    padding: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  likeButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(228, 215, 244, 1)',
    borderRadius: 5,
    padding: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchContainer: {
    paddingHorizontal: 15,
  },
  searchResultsContainer: {
    padding: 10,
  },
  searchResultsOverlay: {
    position: 'absolute',
    top: 40,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(7, 3, 12, 0.9)',
    padding: 10,
    marginHorizontal: 15,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    zIndex: 1,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.text,
    borderRadius: 10,
  },
  searchInput: {
    flex: 1,
    padding: 12,
    fontSize: 12,
    color: COLORS.background,
  },
  searchIcon: {
    marginLeft: 10,
  },
  searchProfileImage: {
    width: 30,
    height: 30,
    borderRadius: 20,
    marginRight: 10,
    borderWidth: 1,
    borderColor: COLORS.text,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    padding: 10,
    marginBottom: 5,
  },
  searchResultTextContainer: {
    flexDirection: 'column',
  },
  searchResultText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: 'bold',
  },
  searchResultSubtext: {
    color: COLORS.text,
    fontSize: 12,
  },
  friendsSection: {
    marginTop: 20,
    paddingHorizontal: 15,
  },
  friendTile: {
    backgroundColor: COLORS.text,
    borderRadius: 10,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  bannerContainer: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.text,
  },
  bannerText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.text,
  },
  friendPhoto: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: COLORS.primary,
    marginRight: 10,
  },
  friendName: {
    fontWeight: 'bold',
    color: COLORS.text,
    fontSize: 16,
  },
  friendUsername: {
    color: COLORS.text,
    fontSize: 14,
  },
  friendSong: {
    color: COLORS.background,
    fontSize: 14,
    marginTop: 5,
    flex: 1,
  },
});

export default HomeStyles;
export {styles};
